# Generated by Django 5.2.4 on 2026-05-11 09:32

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('sec_userid', models.CharField(editable=False, max_length=32, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('is_email_verified', models.BooleanField(db_index=True, default=False)),
                ('is_payment_verified', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_image')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook_profile', models.URLField(blank=True, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('present_address', models.TextField(blank=True, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('student_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('enrollment_semester', models.CharField(blank=True, choices=[('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('FALL', 'Fall')], max_length=10, null=True)),
                ('enrollment_year', models.PositiveIntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, choices=[('SWE', 'Software Engineering'), ('CSE', 'Computer Science & Engineering'), ('ITM', 'Information Technology & Management'), ('MCT', 'Multimedia & Creative Technology'), ('CIS', 'Computing & Information System')], max_length=10, null=True)),
                ('batch', models.CharField(blank=True, max_length=20, null=True)),
                ('section', models.CharField(blank=True, max_length=20, null=True)),
                ('professional_skills', models.JSONField(blank=True, default=list)),
                ('organizational_skills', models.JSONField(blank=True, default=list)),
                ('interested_in', models.JSONField(blank=True, default=list)),
                ('other_professional_skill', models.CharField(blank=True, max_length=255, null=True)),
                ('other_organizational_skill', models.CharField(blank=True, max_length=255, null=True)),
                ('other_interest', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
