# Generated by Django 5.2.4 on 2026-05-12 07:06

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='committee_c_slug_c0391c_idx'), models.Index(fields=['is_active'], name='committee_c_is_acti_871d35_idx'), models.Index(fields=['start_date', 'end_date'], name='committee_c_start_d_bfb829_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='committee_term_end_gte_start'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_committee_term')],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('hierarchy_level', models.PositiveIntegerField(db_index=True)),
                ('category', models.CharField(choices=[('advisory', 'Advisory'), ('leadership', 'Leadership'), ('wing_management', 'Wing Management'), ('wing_member', 'Wing Member')], db_index=True, max_length=30)),
                ('is_executive', models.BooleanField(db_index=True, default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['hierarchy_level', 'title'],
                'indexes': [models.Index(fields=['slug'], name='committee_p_slug_4e5efb_idx'), models.Index(fields=['category', 'hierarchy_level'], name='committee_p_categor_00fd1a_idx'), models.Index(fields=['is_executive'], name='committee_p_is_exec_9c80b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Wing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('banner_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='wing_banner_image')),
                ('icon', models.CharField(blank=True, max_length=120, null=True)),
                ('establishment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='committee_w_slug_4826f2_idx'), models.Index(fields=['name'], name='committee_w_name_cff63e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='committee_assignments', to=settings.AUTH_USER_MODEL)),
                ('committee_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='committee.committeeterm')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='committee.position')),
                ('wing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='committee.wing')),
            ],
            options={
                'ordering': ['-assigned_at', '-created_at'],
                'indexes': [models.Index(fields=['member', 'committee_term'], name='committee_a_member__48144e_idx'), models.Index(fields=['committee_term', 'wing'], name='committee_a_committ_e16c58_idx'), models.Index(fields=['committee_term', 'position'], name='committee_a_committ_cb810b_idx'), models.Index(fields=['is_active', 'assigned_at'], name='committee_a_is_acti_6f414a_idx'), models.Index(fields=['committee_term', 'is_active'], name='committee_a_committ_af4563_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('wing__isnull', True)), fields=('member', 'committee_term', 'position'), name='unique_assignment_without_wing'), models.UniqueConstraint(condition=models.Q(('wing__isnull', False)), fields=('member', 'committee_term', 'wing', 'position'), name='unique_assignment_with_wing')],
            },
        ),
    ]
