# Generated by Django 5.2.4 on 2026-05-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('member_registration_yearly', 'Member Registration - Yearly'), ('member_registration_full', 'Member Registration - Full Studentship'), ('event_registration', 'Event Registration'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
